fix: correctly assign null if target is nullable instead of throwing
riok/mapperly pull request #1191
Opened 2024-03-20 04:02 UTC by latonz

Closes #1182

2024-03-21 06:12 UTC, ni507 requested changes

2024-03-21 06:12 UTC, ni507 commented on test/Riok.Mapperly.Tests/Mapping/ObjectPropertyNullableTest.cs
> +            "class C { public string V {get; set; } }",
missing space `{get; set; }`

2024-03-21 06:12 UTC, ni507 commented on test/Riok.Mapperly.Tests/Mapping/ObjectPropertyNullableTest.cs
> +            "class C { public string V {get; set; } public string Flattened { get; set; } }",
missing space `{get; set; }`

2024-03-21 18:12 UTC, latonz commented on test/Riok.Mapperly.Tests/Mapping/ObjectPropertyNullableTest.cs
> +            "class C { public string V {get; set; } public string Flattened { get; set; } }",
fixed all of them 😊

2024-03-21 18:12 UTC, latonz commented on test/Riok.Mapperly.Tests/Mapping/ObjectPropertyNullableTest.cs
> +            "class C { public string V {get; set; } }",
fixed all of them 😊

2024-03-25 06:05 UTC, ni507 approved these changes

2024-03-25 06:05 UTC, merged