Fix failing projection with static mapper from another assembly
riok/mapperly pull request #1418
Opened 2024-07-26 08:06 UTC by trejjam

# <Title>

## Description

A static mapper from another assembly halts the source generator in "IDE" mode. This PR resolves this issue.

## Checklist

- [x] The existing code style is followed
- [ ] The commit message follows our guidelines
- [x] Performed a self-review of my code
- [x] Hard-to-understand areas of my code are commented
- [x] The documentation is updated (as applicable)
- [x] Unit tests are added/updated
- [x] Integration tests are added/updated (as applicable, especially if feature/bug depends on roslyn or framework version in use)

2024-07-26 10:07 UTC, trejjam commented
More context here:
https://github.com/dotnet/roslyn/issues/73964

2024-08-03 02:16 UTC, latonz requested changes
Thanks for this great contribution! TIL about referenced compilations 😊
I added my feedback, looking forward to get this into main 👍

2024-08-03 02:16 UTC, latonz commented on src/Riok.Mapperly/SyntaxProvider.Roslyn4.0.cs
> +    ) =>
In this codebase we usually use method block bodies for multi-line bodies.

2024-08-03 02:16 UTC, latonz commented on src/Riok.Mapperly/SyntaxProvider.Roslyn4.0.cs
> +            .Collect();
Couldn't this be simplified to
```csharp
context
            .GetMetadataReferencesProvider()
            .Select((metadataReference, _) => (metadataReference as CompilationReference)?.Compilation)
            .WhereNotNull()
            .Collect();
```

Or maybe even introduce a `OfType` extension method similar to the one of linq?
```csharp

context
            .GetMetadataReferencesProvider()
            .OfType<CompilationReference>()
            .Select((compilationReference, _) => compilationReference.Compilation)
            .Collect();
```

2024-08-03 02:16 UTC, latonz commented on src/Riok.Mapperly/SyntaxProvider.Roslyn4.4.cs
> +            .Collect();
Why the not-null assertion + where `not null`?
Probably simplify to
```csharp
context
            .MetadataReferencesProvider
            .Select((metadataReference, _) => (metadataReference as CompilationReference)?.Compilation)
            .WhereNotNull()
            .Collect();
```
or use the same new `OfType` extension method proposed in the comment for roslyn 4.0.

2024-08-03 02:16 UTC, latonz commented on test/Riok.Mapperly.Tests/Mapping/UseStaticMapperTest.cs
> +    public void UseStaticGenericMapperStaticMethodFromAnotherAssembly(bool asCompilationReference)
I think the readability here would be improved if the common code is extracted in a method and two separate tests are created.

2024-08-03 02:41 UTC, latonz commented
Rel. https://github.com/riok/mapperly/issues/1406

2024-08-03 14:35 UTC, latonz commented on src/Riok.Mapperly/SyntaxProvider.Roslyn4.0.cs
> +            .Collect();
Not as nice as I had imagined due to the incremental values provider not having covariance but IMO still easier to read than the previous approach, thanks for updating 😊

2024-08-03 14:36 UTC, latonz approved these changes

2024-08-03 14:36 UTC, merged