Fix crash when object to object mapping
riok/mapperly pull request #340
Opened 2023-04-14 19:52 UTC by TimothyMakkison

Resolves #313

Resolve ide hanging/crash when object to object mapping when deep clone is enabled. I mentioned my concerns in the issue, is it correct for a simple copy to be used when deep cloning is enabled? Should I instead make this a diagnostic errror or would updating the docs and adding a note to the `UseDeepCloning` attribute be enough?

- Added another branch to `SpecialTypeMappingBuilder` for object->object edge case
- Added object->object and object?->object? tests

2023-04-15 10:41 UTC, latonz requested changes
Looks good to me, as you already considered, I'd introduce a diagnostic for this case `object mapped to another object without deep clone` with a default severity of Info.

The commit message indicates that this is a feature. I'd say this is more of a bug fix and therefore the commit message should start with `fix: `

2023-04-15 14:41 UTC, TimothyMakkison commented
Keep getting RS2007, where should I put the new rule?

2023-04-16 08:57 UTC, latonz commented
> Keep getting RS2007, where should I put the new rule?

I think the format of the unshipped file is missing the release header. However, you can add it to the shipped file directly anyway.

2023-04-16 11:55 UTC, TimothyMakkison commented
I was eventually able to add it to the unshipped file 😅
I'll move the rule to shipped under the new release 2.9

2023-04-16 12:00 UTC, latonz commented
The upcoming release is 2.8.0 not 2.9.0. You can add it to 2.8.0

2023-04-17 11:07 UTC, merged