Fix unmanaged member deep cloning on .NET Framework.
riok/mapperly pull request #388
Opened 2023-04-28 09:03 UTC by TimothyMakkison

Resolves #362. `UseDeepCloning` with primitive members would work on .NET Core but failed on .NET Framework. 

Normally Mapperly generates a mapping with `DirectAssignmentMappingBuilder` when `ctx.Source.IsImmutable()` returns true. `IsImmutable` checks if the value is `IsReadonly` in .net core all primitive types are `readonly struct` whereas in .net framework they are `structs`, thus returning `IsReadonly`: `false`.
 By adding an `IsUnmanaged` check, `IsUmmutable` should work on .NET Framework and will use shortcuts for user defined unmanaged structs.

- Add `IsUnmanaged` check to `IsImmutable`
- Update struct tests to be managed types and add corresponding unmanaged tests

2023-04-28 09:18 UTC, latonz requested changes
Thank you for the contribution 🎉 . .NET Framework issues are hard to debug for me, since I don't have a windows machine 🙈  (probably I should create windows vm someday 😊 )

Could you add an integration test for this? Would be helpful to really test this, as the unit tests only run on the latest target framework but integration tests also run on .NET Framework. You could use https://github.com/latonz/mapperly/pull/14 as a starting point for the integration test (I did that a few days ago to start investigating this issue).

2023-04-28 09:18 UTC, latonz commented on test/Riok.Mapperly.Tests/Mapping/CastTest.cs
> +            """
Weird indention.

2023-04-28 13:41 UTC, TimothyMakkison commented on test/Riok.Mapperly.Tests/Mapping/ObjectPropertyTest.cs
> +        TestHelper.GenerateMapper(source).Should().HaveSingleMethodBody("return source;");
The test checks that ref structs can deep clone. Because all ref structs are unmanaged, all copies are deep clones. I can remove it.

2023-04-28 21:30 UTC, TimothyMakkison commented
I'll look at the test and possible remove the `IsReadonly` check as it can generate invalid code. Is `IsImmutable` a misleading name? Here we use it to check if a type is a pseudo primitive/readonly/non reference containing type.

I've found a potential unrelated mapping bug with `Span<T>` fields. Mapperly correctly copies ref fields in ref structs but will fail to do a deep clone of `Span<T>` or `ReadOnlySpan<T>` fields. Its debatable wherther this is a bug or not, although I think this is unexpected and a clone should be done.

For example
```C#
ref struct MyStruct{
Span<MyStruct> Collection;
}

public static partial global::Riok.Mapperly.Sample.MyRefStruct Map(global::Riok.Mapperly.Sample.MyRefStruct car)
{
    var target = new global::Riok.Mapperly.Sample.MyRefStruct();
    target.Collection = car.Collection;
    return target;
}
```

2023-04-29 10:43 UTC, latonz commented
In what scenario the is readonly check can lead to invalid generated code? Are you referring to readonly types containing properties which are of a mutable type? This could actually be a problem with the current implementation 🤔
I think `IsImmutable` fits as a name, as this is used to decide whether a clone is needed when `UseDeepCloning` is `true`. A type which is truely immutable doesn't need to be copied even when `UseDeepCloning` is `true`.
This check could even be improved further to take well known immutable types (eg. the immutable collections) into account, however, it always needs to be checked that for example the types in the list are immutable too.

Summarising I would keep this PR only fixing the unmanaged type / .NET Framework problem and create other issues / PR's for the arisen problems.

2023-04-29 13:07 UTC, TimothyMakkison commented
> In what scenario the is readonly check can lead to invalid generated code? Are you referring to readonly types containing properties which are of a mutable type? This could actually be a problem with the current implementation 🤔

Just checked it. A readonly struct will do a direct assignment or return, even if it contains cloneable properties like an array of types.
```C#
public readonly struct A
{
    public readonly int[] Value { get; init; }
}
public static partial global::Riok.Mapperly.Sample.A Map(global::Riok.Mapperly.Sample.A source)
{
    return source;
}
```
> I think IsImmutable fits as a name, as this is used to decide whether a clone is needed when UseDeepCloning is true. A type which is truely immutable doesn't need to be copied even when UseDeepCloning is true.

tbh I'm bike shedding over the name. I kept looking up defintions of blittable/unmanaged types trying to think of a better one  😄. To borrow from rust; what we are checking for is whether we can `copy` or have to `clone` the type. I don't think immutability is relevant (except in the case of immutable reference types like `string`). 

> This check could even be improved further to take well known immutable types (eg. the immutable collections) into account, however, it always needs to be checked that for example the types in the list are immutable too.

Yeah I'm not sure how to handle this. Do Immutable types avoid boxing structs?

> Summarising I would keep this PR only fixing the unmanaged type / .NET Framework problem and create other issues / PR's for the arisen problems.

👍 I'll take a look at the span problem or create an issue.

2023-04-29 15:35 UTC, TimothyMakkison commented
Okay I've removed the `IsReadOnly` check, I'll create issues for the `Span<T>` problem and for optimizing copyable structs that contain string members.

2023-04-30 15:42 UTC, latonz approved these changes

2023-04-30 15:43 UTC, merged