feat: use .Net 8 ToDictionary overload
riok/mapperly pull request #755
Opened 2023-09-15 10:38 UTC by TimothyMakkison

# Use .Net 8 ToDictionary overload

## Description
Use the `ToDictionary` overload if key and value mapping is synthetic. 

```C#
// New
return global::System.Collections.Generic.Enumerable.ToDictionary(source);

// Old
var target = new global::System.Collections.Generic.Dictionary<string, long>(source.Count);
foreach (var item in source)
{
    target[item.Key] = item.Value;
}
return target;
```

See #689 

## Checklist

- [ ] The existing code style is followed
- [ ] The commit message follows our guidelines
- [ ] Performed a self-review of my code
- [ ] Hard-to-understand areas of my code are commented
- [ ] The documentation is updated (as applicable)
- [ ] Unit tests are added/updated
- [ ] Integration tests are added/updated (as applicable, especially if feature/bug depends on roslyn or framework version in use)

2023-09-15 11:43 UTC, latonz requested changes
Thank you for this PR 😊

2023-09-15 11:43 UTC, latonz commented on src/Riok.Mapperly/Descriptors/MappingBuilders/DictionaryMappingBuilder.cs
> +    private const string ToDictionaryMethodName = "global::System.Collections.Generic.Enumerable.ToDictionary";
Both are method names aren't they? I think names `ToDictionaryMethodName` and `ToDictionaryMethodFullName` would make things clearer, wdyt?

2023-09-15 13:05 UTC, TimothyMakkison commented
On second thoughts, should I close this PR and use the `Dictionary<TKey, TValue>(IEnumerable<KeyValuePair<TKey, TValue>)` instead. This extension is just a wrapper for it, plus the constructor is available on all of .Net excluding .Net Standard 2.0.

I was planning on later refactoring this when I add a version detector class for #732 and to speed up checks for versioned methods

2023-09-15 13:06 UTC, TimothyMakkison commented
On second thoughts, should I close this PR and use the `Dictionary<TKey, TValue>(IEnumerable<KeyValuePair<TKey, TValue>)` instead. This extension is just a wrapper for it, plus the constructor is available on all of .Net excluding .Net Standard 2.0.

I was planning on later refactoring this when I add a version detector class for #732 and to speed up checks for versioned methods

2023-09-15 13:29 UTC, latonz commented
IMO if it is just a wrapper for the ctor we should use the ctor directly.

2023-09-19 08:30 UTC, latonz requested changes

2023-09-19 16:06 UTC, latonz requested changes

2023-09-19 16:06 UTC, latonz commented on src/Riok.Mapperly/Descriptors/MappingBuilders/DictionaryMappingBuilder.cs
> +        // use .NET 8  method .ToDictionary() if value and key mapping is synthetic
This is not yet fixed, is it?

2023-09-19 16:06 UTC, latonz commented on src/Riok.Mapperly/Descriptors/MappingBuilders/DictionaryMappingBuilder.cs
> +                x is { Parameters.Length: 1 }
This code base usually uses pattern matching only for multiple conditions and/or type checks. Probably use `x.Parameters.Length == 1` here.

2023-09-20 06:04 UTC, latonz approved these changes

2023-09-20 06:13 UTC, latonz approved these changes

2023-09-20 06:19 UTC, merged