feat: fix incorrect `private set` when `~MemberVisibility.Accessible` is used
riok/mapperly pull request #933
Opened 2023-11-20 22:27 UTC by TimothyMakkison

# feat: fix incorrect `private set` when `~MemberVisibility.Accessible` is used

## Description
Prevents the invalid generation of set to a `private set` property if `~MemberVisibility.Accessible` is used.

Fixes #932

## Checklist

- [ ] The existing code style is followed
- [ ] The commit message follows our guidelines
- [ ] Performed a self-review of my code
- [ ] Hard-to-understand areas of my code are commented
- [ ] The documentation is updated (as applicable)
- [ ] Unit tests are added/updated
- [ ] Integration tests are added/updated (as applicable, especially if feature/bug depends on roslyn or framework version in use)

2023-11-21 03:30 UTC, latonz requested changes
Thank you for this fast bugfix 😊

2023-11-21 03:30 UTC, latonz commented on test/Riok.Mapperly.Tests/Mapping/UnsafeAccessorTest.cs
> +                partial B Map(A source);
This has weird indention… align the entire raw string at the same indention. Same for the other test.

2023-11-21 12:28 UTC, latonz approved these changes

2023-11-21 12:29 UTC, merged

2023-11-22 12:09 UTC, mentallabyrinth commented
Thank you for the fast fix! Do you have an ETA on when the next release will be available in nuget?

2023-11-22 12:26 UTC, latonz commented
A preview release including this bug fix is published. We don't have an ETA on the next stable release, probably in a couple weeks.

2023-11-22 13:33 UTC, mentallabyrinth commented
Thank you very much!