feat: support MapProperty with nameof for CtorMapping
riok/mapperly pull request #957
Opened 2023-11-28 19:43 UTC by trejjam

# Constructor mapping with `MapProperty` and `nameof`

## Description

Support for
```cs
public class Mapping
{
    [MapProperty(nameof(A.BId), nameof(B.Id))] // notice target ctor parameter is "id", but `MapProperty` target is "Id"
    private partial B Map(A source);
}

class A
{
    public long BId { get; }
}

class B
{
    public long Id { get; }

    public B(long id) { Id = id; }
}
```

Fixes # 952

## Checklist

- [x] The existing code style is followed
- [x] The commit message follows our guidelines
- [x] Performed a self-review of my code
- [x] Hard-to-understand areas of my code are commented
- [x] The documentation is updated (as applicable)
- [x] Unit tests are added/updated
- [x] Integration tests are added/updated (as applicable, especially if feature/bug depends on roslyn or framework version in use)

2023-12-02 15:56 UTC, latonz requested changes
Thank you for this contribution!

2023-12-02 19:55 UTC, trejjam commented on src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/INewInstanceBuilderContext.cs
> +    Dictionary<string, string> MemberConfigsByRootTargetNameCaseInsensitiveMapping { get; }
Naming is not always my thing 😄. Sorry for though moments though

2023-12-02 19:55 UTC, trejjam commented on src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/INewInstanceBuilderContext.cs
> +    Dictionary<string, string> MemberConfigsByRootTargetNameCaseInsensitiveMapping { get; }
Thank you for proposing it

2023-12-02 20:06 UTC, trejjam commented on src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/NewInstanceBuilderContext.cs
> +        }
When I remove the removal I receive `RMG005`. It happens only in `NewInstanceContainerBuilderContext`, I do not have a bigger insight into ValueTuple mapping. But I guess the validation works the same way as here in `NewInstanceBuilderContext`.

Without using the mapping I have the `RMG005` also.

2023-12-04 16:03 UTC, latonz requested changes
Thank you for the updates 😊

2023-12-04 16:03 UTC, latonz commented on src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/NewInstanceBuilderContext.cs
> +        }
That totally makes sense, I overlooked the remove was there before.

But now I am wondering on why to add if condition at all and not sth. like this:
```c#
var paramName = RootTargetNameCasingMapping.GetValueOrDefault(mapping.Parameter.Name) ?? mapping.Parameter.Name;
MemberConfigsByRootTargetName.Remove(paramName);
```
It actually shouldn't make any difference, as for a given parameter name a case insensitive match should always be found.
I'd either add a comment which explains that the if should always match, throw an exception in an else clause or use the syntax above. IMO the syntax above should be the most reliable while still being easy to read.

2023-12-05 20:08 UTC, trejjam commented on src/Riok.Mapperly/Descriptors/MappingBodyBuilders/BuilderContext/NewInstanceBuilderContext.cs
> +        }
I used the `GetValueOrDefault`, but it should be the same:
![image](https://github.com/riok/mapperly/assets/3594540/84e063a1-249a-47db-9719-267450929371)

2023-12-06 11:56 UTC, merged