fix: get mapper defaults for roslyn version smaller 4.4
riok/mapperly pull request #958
Opened 2023-11-29 16:32 UTC by ni507

Fixes # 946

2023-12-01 12:14 UTC, latonz requested changes

2023-12-05 06:39 UTC, ni507 commented on test/Riok.Mapperly.IntegrationTests/EnumMapperTest.cs
> +            return Verifier.Verify(enum2);
Changed.

2023-12-05 06:39 UTC, ni507 commented on test/Riok.Mapperly.IntegrationTests/Mapper/EnumMapper.cs
> +    }
Changed.

2023-12-05 06:39 UTC, ni507 commented on test/Riok.Mapperly.IntegrationTests/Mapper/EnumMapper.cs
> +[assembly: MapperDefaults(EnumMappingStrategy = EnumMappingStrategy.ByName)]
Changed.

2023-12-05 06:39 UTC, ni507 commented on test/Riok.Mapperly.IntegrationTests/EnumMapperTest.cs
> +    public class EnumMapperTest : BaseMapperTest
Changed.

2023-12-05 06:40 UTC, ni507 commented on test/Riok.Mapperly.IntegrationTests/EnumMapperTest.cs
> +        [VersionedSnapshot(Versions.NET7_0)]
Changed.

2023-12-06 09:57 UTC, merged